tap 'beeftornado/rmtree'
brew 'ack'
brew 'git'
brew 'amazon-ecs-cli'
brew 'python3'
brew 'asciinema'
brew 'python'
brew 'little-cms'
brew 'asciinema2gif'
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'bdw-gc'
brew 'binutils'
brew 'boost'
brew 'certbot'
brew 'coreutils'
brew 'ctags'
brew 'gnutls'
brew 'emacs'
brew 'findutils', args: ['with-default-names']
brew 'gawk'
brew 'gnu-indent', args: ['with-default-names']
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar', args: ['with-default-names']
brew 'gnu-which', args: ['with-default-names']
brew 'gsl'
brew 'gtkmm'
brew 'htop'
brew 'jq'
brew 'lynx'
brew 'node'
brew 'parallel'
brew 'plantuml'
brew 'popt'
brew 'rbenv'
brew 'rsstail'
brew 'sox', args: ['with-flac', 'with-lame', 'with-libvorbis']
brew 'subversion'
brew 'syncthing'
brew 'syncthing-inotify'
brew 'tmux'
brew 'todo-txt'
brew 'tree'
brew 'vim', args: ['with-lua', 'with-override-system-vi']
brew 'watch'
brew 'wdiff', args: ['with-gettext']
brew 'wget'
brew 'zsh'
brew 'beeftornado/rmtree/brew-rmtree'
brew 'beeftornado/rmtree/brew-rmtree'
brew 'go-delve/delve/delve'
brew 'homebrew/dupes/diffutils'
brew 'homebrew/dupes/ed', args: ['with-default-names']
brew 'homebrew/dupes/file-formula'
brew 'homebrew/dupes/gpatch'
brew 'homebrew/dupes/grep', args: ['with-default-names']
brew 'homebrew/dupes/gzip'
brew 'homebrew/dupes/less'
brew 'homebrew/dupes/m4'
brew 'homebrew/dupes/make'
brew 'homebrew/dupes/nano'
brew 'homebrew/dupes/openssh'
brew 'homebrew/dupes/rsync'
brew 'homebrew/dupes/screen'
brew 'homebrew/dupes/unzip'
brew 'neovim/neovim/neovim'
brew 'vitorgalvao/tiny-scripts/cask-repair'
